version: '3'

services:
  api:
    build:
      context: .
    ports:
     - "8201:8201"
    volumes:
      - ./:/code
    working_dir: /code
    command: uvicorn order_api:app --host 0.0.0.0 --port 8201 --reload

networks:
  default:
    external:
      name: user-order-network
