version: '3'

services:
  api:
    build:
      context: .
    ports:
     - "8200:8200"
    volumes:
      - ./:/code
    working_dir: /code
    command: uvicorn user_api:app --host 0.0.0.0 --port 8200 --reload

networks:
  default:
    external:
      name: user-order-network
